ALTER TABLE file MODIFY COLUMN `name` VARCHAR (128);
ALTER TABLE file MODIFY COLUMN `file_key` VARCHAR (128);
ALTER TABLE file MODIFY COLUMN `storage_url` VARCHAR (256);
ALTER TABLE file MODIFY COLUMN `visit_url` VARCHAR (256);